### PR TITLE
Only add symbol to source when called with `.for()`

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by ljharb** [comment]
(ignore the test failure; if you rebase on latest master it will run tests on 0.10 instead of 0.1)

**Comment by JakeChampion** [comment]
@ljharb @WebReflection

Finally got around to looking into this. All tests pass on CI now, I also added two tests to cover the feature I was adding :-)

**Comment by WebReflection** [comment]
Can't do full review but for what I can see LGTM

**Comment by JakeChampion** [comment]
I will break the commits up into two commits, first one will add the tests (should fail on ci) and the second will add the feature (should pass on ci).

**Pull request merged**
